### ISSUE TITLE
[BUG] Entire persisted settings UI fails to initialize on startup (v21.33 dev)

### ISSUE THREAD

**Issue by JesseG689** [vadash/Extension-Summaryception#4]
## Description

After updating Summaryception `dev` from v21.23 to v21.33, the Summaryception settings UI stopped initializing from the persisted settings.

The underlying Summaryception configuration is still present correctly in SillyTavern's saved `settings.json`.

Examples:

- Checkboxes persisted as `true` appear unchecked.
- `uiMode: advanced` is not reflected in the UI.
- `memoryMode: append_only` is not reflected in the UI.
- Injection/template textareas are blank.
- The Append Only System Block Template is blank.
- Summarizer prompt/template textareas are blank.
- Other saved values are likewise not reflected in the settings panel.

Example values that are still correctly persisted in `settings.json` include:

- `enabled: true`
- `uiMode: advanced`
- `memoryMode: append_only`
- `stateCatGmNotes: true`
- `stateCatLocation: true`
- `applyRegexScripts: true`
- `hideNonTextMessages: true`
- `stripChineseIdeographs: true`

Adding an explicit `await updateUI();` immediately after the settings UI is initialized causes all of the persisted controls and textareas to display correctly again without making any changes to `settings.json`.

## Steps to reproduce

1. Start with an existing configured Summaryception v21.23 installation.
2. Update the `dev` branch to v21.33.
3. Reload SillyTavern.
4. Open `Settings → Summaryception`.
5. Observe that the saved settings are not reflected in the UI. Checkboxes/radios are unselected and template/prompt textareas are blank.

As a test/workaround, I modified `index.js` from:

```js
initSettingsTabs();
initConnectionUI();
await registerSummaryceptionMemoryMacro();
```

to:

```js
initSettingsTabs();
initConnectionUI();
await updateUI();
await registerSummaryceptionMemoryMacro();
```

After refreshing SillyTavern, the complete settings UI immediately displayed the persisted values correctly.

## Expected behavior

When SillyTavern loads, the Summaryception settings panel should be initialized from the existing persisted Summaryception configuration.

Saved checkbox/radio states should be selected appropriately, and saved/default template and prompt textareas should contain their expected content.

## Actual behavior

The Summaryception settings panel itself loads, but its controls appear to remain in an uninitialized/default HTML state.

This includes more than checkboxes:

- saved checkboxes appear unchecked
- mode selections are not reflected
- memory mode is not reflected
- template textareas are blank
- prompt textareas are blank

The actual persisted settings remain intact in SillyTavern's `settings.json`.

Adding a single explicit:

```js
await updateUI();
```

immediately after `initConnectionUI()` fixes the complete settings display on the same installation with the same persisted settings.

I have not captured an F12 console error yet because I reproduced and diagnosed this while using SillyTavern from my phone.

From inspection of the current code, `updateUI()` normally calls `syncSettingsInputs()`, which populates the settings controls and template/prompt textareas. The normal startup UI refresh appears to happen only after the APP_READY loaded-chat reconciliation path completes.

This makes me suspect that the initial `updateUI()` call is not being reached during startup on my installation, although I have not yet identified which part of reconciliation is responsible.

SillyTavern's `APP_READY` event itself appears to support late listeners, so I do not believe this is simply a missed APP_READY event.

## Environment

- Summaryception version: v21.33.0 (`dev`) — originally reproduced on v21.32.0 after updating from v21.23
- SillyTavern version: 1.18.0
- Connection source (Default / OpenAI / Ollama / Connection Profile): Connection Profile
- Browser (or platform): iPhone / iOS, accessing the SillyTavern web UI

## Additional context

- Logs: No Trace Mode/F12 console log captured yet because I reproduced this while using SillyTavern from an iPhone. I can provide additional logs if needed.
- Custom prompt preset (if any): None. Using the built-in `Narrative` prompt preset.
- The saved Summaryception settings were independently checked in SillyTavern's `settings.json` and were still intact.

**Comment by JesseG689** [comment]
I found the underlying cause of this on my setup, and it appears to be more than just a UI synchronization problem.

I'm currently on v21.35.0. After my chat grew large enough to require its first automatic summary, Summaryception still showed 0 snippets / 0 ghosted even though the status indicated:

- Verbatim Window: ~35k / 22k
- Backlog: 8
- Queued source: ~15k / 16k

With Debug Mode enabled, the automatic worker exposed the actual exception:

```text
[Summaryception] Error while ending foreground generation: TypeError: globalThis.crypto.randomUUID is not a function
    at ensureMessageScId (message-identity.js:16:43)
    at ensureChatScIds (message-identity.js:32:20)
    at prepareSummaryCycle (summary-preflight.js:13:22)
    at runElasticAutoCycle (summarizer-engine.js:68:28)
```

`src/foundation/message-identity.js` currently assigns IDs with:

```js
chatMessage.sc_id = globalThis.crypto.randomUUID();
```

In my browser environment `crypto` exists, but `crypto.randomUUID()` is not available.

This explains the original UI symptom on my setup as well. Loaded-chat reconciliation calls `ensureChatScIds()` before it reaches the final `updateUI()`. When `randomUUID()` throws, reconciliation exits early, so persisted settings/status gauges are never synchronized to the UI. My earlier workaround of calling `await updateUI()` immediately after `initConnectionUI()` only masked that symptom.

It also prevents automatic summarization entirely because `prepareSummaryCycle()` calls `ensureChatScIds()` before the summarization planner can run.

I patched `ensureMessageScId()` to use a fallback ID generator:

1. Use `crypto.randomUUID()` when available.
2. Otherwise use `crypto.getRandomValues()` to construct a UUID v4.
3. Fall back to a timestamp/random ID only if neither crypto method is available.

After applying that patch and reloading SillyTavern, the existing backlog immediately summarized successfully:

```text
[Summaryception] [DEBUG] Visible assistant turns: 17, max batch: 8, verbatim budget: 35k/22k tokens, summary budget: 15k/16k tokens
[Summaryception] Summarizing 8 assistant turns (indices 0–21)
[Summaryception] [DEBUG] LLM call #1 CHAT -> L0 turns 0-21: input 15k, prompt 1k, output 338
[Summaryception] [DEBUG] Memory updated: inject 257 tokens; layers L0=1
[Summaryception] [DEBUG] Visible assistant turns: 9, max batch: 8, verbatim budget: 20k/22k tokens, summary budget: 0/16k tokens
```

So the fix restored both:

- loaded-chat UI/status synchronization
- automatic Layer 0 summarization

I also checked the current dev branch (v22.5.0 at the time of testing), and `message-identity.js` still contains the same unconditional `globalThis.crypto.randomUUID()` call, so this appears to still be present there as well.

A defensive `randomUUID()` fallback in `ensureMessageScId()` should resolve the root issue for environments where that API is unavailable.

**Comment by kuss-ms** [comment]
I got the same problem and I was forced to patch it myself by replacing crypto.randomUUID with a small custom function. Would be nice if this is fixed.

The reason why randomUUID is not available sometimes is HTTPS vs HTTP. Running ST over HTTPS makes no sense for me.

Source: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

**Comment by vadash** [comment]
> *This was generated by AI during triage.*

Root cause confirmed identical to #8: `crypto.randomUUID` exists only in secure contexts, so on plain-HTTP deployments `ensureChatScIds()` throws inside `reconcileLoadedChatState()` — aborting startup reconciliation *before* the UI refresh runs, which is why the whole settings panel appears uninitialized while the persisted values in `settings.json` stay intact. The same throw breaks auto summarization.

Thanks for the excellent diagnosis and the validated fallback patch — it matches the fix now specified in #8's agent brief (fallback UUID + visible manual-run failure notice), which repairs all `ensureChatScIds` callsites at once.

Closing as a duplicate of #8; follow progress there.
